### ISSUE TITLE
Ubuntu 18.0.4 Documentation

### ISSUE THREAD

**Issue by stick** [openmicroscopy/ome-documentation#1967]
Documentation updates for installation on Ubuntu 18.0.4

Two main issues: 
1. no ice binaries available from ZeroC
2. SSL version requires changes to Ciphers

A small changes that may not be 18.0.4 specific
1. Default nginx enabled config conflicts with default generated omero config
* fix by `rm -vf /etc/nginx/sites-enabled/default

We've handled the ice issues by cloning the 3.6.4 tag from their git repository and building it from source.

```
    - name: Clone zeroc ice repository
      git:
        repo: "https://github.com/zeroc-ice/ice.git"
        version: "v3.6.4"
        dest: /srv/zeroc-ice36/
      tags: build

    - name: Build zeroc ic
      command: make cpp
      args:
        chdir: /srv/zeroc-ice36
        creates: /srv/zeroc-ice36/cpp/bin/icegridnode
      tags: build

    - name: make install zeroc ice cpp bindings
      command: make install
      args:
        chdir: /srv/zeroc-ice36/cpp
        creates: /opt/Ice-3.6.4/LICENSE
      tags: build

    - name: symlink versioned ice directory
      file:
        state: link
        src: "/opt/Ice-{{ ice_version_long }}"
        dest: /opt/ice
      tags: ice
```

This provides enough of the ice infrastructure to build the python module and run the server.  It's probably not sufficient to build OMERO.

Adjusting the ciphers to compensate for the OpenSSL version has been cribbed from the Debian instructions.

https://docs.openmicroscopy.org/omero/5.4.10/sysadmins/unix/server-debian9-ice36.html#patching-omero-server
